# Generated by Django 3.0.4 on 2020-04-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlementType', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
