# Generated by Django 3.0.4 on 2020-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
