# Generated by Django 3.0.4 on 2020-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20200513_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
