# Generated by Django 3.0.7 on 2020-09-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20200521_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactiontrait',
            old_name='trait',
            new_name='description',
        ),
    ]
