# Generated by Django 3.0.7 on 2020-09-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_auto_20200909_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactiontrait',
            old_name='description',
            new_name='trait',
        ),
    ]
