# Generated by Django 3.0.4 on 2020-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political_formation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalformation',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='politicalformation',
            name='governing_body',
        ),
        migrations.RemoveField(
            model_name='politicalformation',
            name='government',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Government',
        ),
        migrations.DeleteModel(
            name='PoliticalFormation',
        ),
    ]
