# Generated by Django 3.0.7 on 2020-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_formation', '0003_classification_government_politicalformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalformation',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
