# Generated by Django 3.0.7 on 2020-09-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_formation', '0005_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalformation',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicalformation_inclusion', to='political_formation.PoliticalFormation'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
