# Generated by Django 3.0.4 on 2020-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
