# Generated by Django 3.0.4 on 2020-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
