# Generated by Django 3.0.4 on 2020-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0004_title_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='current_holder',
            field=models.BooleanField(default=False),
        ),
    ]
