# Generated by Django 3.0.4 on 2020-07-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20200521_1332'),
        ('title', '0005_title_current_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_holder', to='character.Character'),
        ),
    ]
