# Generated by Django 3.0.7 on 2020-09-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0006_auto_20200713_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
