# Generated by Django 3.0.7 on 2020-09-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20200909_1819'),
        ('title', '0007_auto_20200910_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='current_holder',
        ),
        migrations.RemoveField(
            model_name='title',
            name='holders',
        ),
        migrations.AddField(
            model_name='title',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character'),
        ),
    ]
