# Generated by Django 3.0.7 on 2020-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governing_body', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governingbody',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
