# Generated by Django 3.0.4 on 2020-04-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementCharacteristic1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementCharacteristic2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementCharacteristic3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='s_type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='administrative_unit',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='sproperty',
        ),
        migrations.DeleteModel(
            name='AdministrativeUnit',
        ),
        migrations.DeleteModel(
            name='SettlementProperties',
        ),
        migrations.AddField(
            model_name='settlement',
            name='characteristic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.SettlementCharacteristic1'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='characteristic2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.SettlementCharacteristic2'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='characteristic3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.SettlementCharacteristic3'),
        ),
    ]
