# Generated by Django 3.0.4 on 2020-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementtype',
            name='lowerLimit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlementtype',
            name='upperLimit',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
