# Generated by Django 3.0.4 on 2020-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_auto_20200428_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='economyTpye',
        ),
        migrations.AddField(
            model_name='economy',
            name='description',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
