# Generated by Django 3.0.4 on 2020-04-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_auto_20200410_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='SettlementCharacteristic1',
            new_name='Economy',
        ),
        migrations.RenameModel(
            old_name='SettlementCharacteristic2',
            new_name='KnownFor',
        ),
        migrations.RenameField(
            model_name='economy',
            old_name='characteristic',
            new_name='economyTpye',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='characteristic1',
            new_name='economy',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='characteristic2',
            new_name='know_for',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='characteristic3',
        ),
        migrations.DeleteModel(
            name='SettlementCharacteristic3',
        ),
        migrations.AddField(
            model_name='settlement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlement.Location'),
        ),
    ]
