# Generated by Django 3.0.4 on 2020-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0003_auto_20200507_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlementtype',
            name='lowerLimit',
        ),
        migrations.RemoveField(
            model_name='settlementtype',
            name='upperLimit',
        ),
        migrations.AlterField(
            model_name='settlement',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
