# Generated by Django 3.0.4 on 2020-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_auto_20200521_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
