# Generated by Django 3.0.7 on 2020-09-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('political_formation', '0005_relationship'),
        ('settlement', '0006_settlement_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='partof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='political_formation.PoliticalFormation'),
        ),
    ]
